### ISSUE TITLE
Wocket v1 (Release Date: TBD)

### ISSUE THREAD

**Issue by crookse** [drashland/wocket#53]
- [x] Prep documentation at https://drash.land/sockets (currently in staging: https://drash.land/sockets/staging)
    - [x] Review on mobile
- [x] Fix integration tests (#66)
    - [x] Move example apps to integration tests folder and turn them into integration tests
- [x] Add tutorials in documentation
- [x] Send message when closing a channel (#57)
- [x] Clients shouldn't be able to send messages they're not connected to (#65)
- [x] Update to latest deno version
- [x] Documentation (https://github.com/drashland/website/issues/213)

**Comment by ebebbington** [comment]
!!! 🎉 🚀

**Comment by ebebbington** [comment]
Update to deno v1.2.0 before release?

**Comment by crookse** [comment]
> Update to deno v1.2.0 before release?

This PR now uses Deno v1.2.0

**Comment by crookse** [comment]
Changing this to 2021 Semester 2. It was discovered that Wocket's implementation of "queueing messages" wasn't fully developed and there needs to be more planning about how Wocket handles queuing messages (in the server, in channels, and possibly client to client cases).
